# config.yaml
model:
  name: cfqkbnc
  block_type: base
  num_classes: 10
teacher:
  name: cfqkbnc_deep
  block_type: acb
  num_classes: 10
  path: xxx
  KD: True

training:
  batch_size: 128
  epochs: 50
  learning_rate: 0.001