# config.yaml
model:
  name: cfqkbnc
  block_type: base
  num_classes: 10
  ckpt: /content/ADLS/2025-03-27/cfqkbnc_base_kd_cfqkbnc_deep_acb_feature
teacher:
  teacher_net: cfqkbnc_deep
  block_type: acb
  num_classes: 10
  kd_loss_scalar: 0.5
  kd_loss_schedular: True
  temperature: 4
  ckpt: /content/ADLS/teacher_model/cfqkbnc_deep_acb_train/latest.pth
  KD: True
  method: logits   #[feature,logits]

training:
  batch_size: 128
  epochs: 50
  learning_rate: 0.001